### ISSUE TITLE
Host database externally

### ISSUE THREAD

**Issue by KthProg** [ITCS2250/HorseFarm#4]
We need persistent hosting for the database to be able to do any serious work. We need the database to be accessible from any external PC.

**Comment by KthProg** [comment]
Database has to be hosted on SQL server 2014.

**Comment by mgargano4** [comment]
I have an older Dell I'm not using, it doesn't currently have windows though. 

-----Original Message-----

**Comment by KthProg** [comment]
As long as you can get it so that the database is accessible externally that's no problem. I think you can get SQL Server 2014 and Windows 8 for free through DreamSpark. I'll send you the link if you need it.

**Comment by KthProg** [comment]
Never mind this issue. I can test here, then we'll wire up at completion.
